name: Azure Web Apps CI/CD

env:
  NODE_VERSION: '12.x'

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - master

jobs:
  build_and_deploy_job:
    name: Login
    runs-on: ubuntu-latest
    steps
    - uses: azure/login@v1.1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - run: |
        az webapp list --query "[?state=='Running']"
  - name: Use Node.js ${{ NODE_VERSION }}
    uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}